version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URL=mongodb://mongodb:27017
    depends_on:
      - mongodb
    restart: unless-stopped
    volumes:
      - ./:/app
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    networks:
      - retirement-network

  mongodb:
    image: mongo:7.0
    ports:
      - "27021:27017"
    environment:
      - MONGO_INITDB_DATABASE=retirement_chatbot
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    restart: unless-stopped
    networks:
      - retirement-network

volumes:
  mongodb_data:

networks:
  retirement-network:
    driver: bridge